# Generated by Django 4.2.8 on 2023-12-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksnipserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='id',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='user',
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
